name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/
    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: make
